### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/encore#3]
Hey,do you recommend to use encore in production?
In my flight booking app

**Comment by ardan-bkennedy** [comment]
I don't have personal experience using the encore tooling for deployment. In the end you don't need them to deploy if you want to manage that yourself.

I really like what they provide, but I know you are already far down your development path. Look at this project more carefully. I'll be happy to jump on another call to discuss.

**Comment by himynamej** [comment]
If you can let's set time to discuss .

**Comment by ardan-bkennedy** [comment]
I have time tomorrow. Try to keep it at 9am-11am Miami time. Send a calendar invite.
