### ISSUE TITLE
Question about convertors 

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/encore#4]
I want to convert one model to enother in my program this is so complicated,I get data from API and I want to convert it to domain model for this I need to use other domains for example API send me a data about airport but just id of it I must convert it to real airport for more data , should I do this in convert method in store level or just in domains?

**Comment by ardan-bkennedy** [comment]
You can't perform a join across domains.  From API to APP, the APP layer models need to accept when data is coming off the transport. The APP layer is your api in struct form. If these two layers are the same. In other words the APP layer is implementing the transport (HTTP) handlers, the following still applies.

From inside the APP layer you want to make BUS layer calls. In this case, the APP layer will need to make BUS calls to create complete BUS data models for the actual calls you want to make. NOW!  you could have your BUS layer APIs take models that are incomplete and then inside of BUS make the calls you need to complete data.

I can jump on a call.

**Comment by himynamej** [comment]
Yes we decided on encore to use .
You set timer when ever you want your mornings times  are great for me

**Comment by ardan-bkennedy** [comment]
Great idea to use Encore.  Did my thoughts help at all?  I like the idea of the business layer completing the data it needs I think. This data is really related to the business logic.

**Comment by himynamej** [comment]
Yeah it's helped a lot ,I saw your video with encore it was so helpful,yeah I agree with this to complete data in business,
And when I want to add temporal can I just write my workflow in app ,I don't want to API run temporal,what do you think about that
And get data from business and handle relationship between business in app,for example call one function and pass out put to enother?

**Comment by himynamej** [comment]
Can we write temporal workflow in app and run business as a activity?
Is that good to run workflow in API or just run it in app

**Comment by ardan-bkennedy** [comment]
I need more information. Can you give me the specifics on the functionality

**Comment by himynamej** [comment]
Buy ticket workflow have a multiple activity like get ticket buy id and increase balance from user and then create ticket , three functions call in another world three activity,and then send result to user , every result of activities store buy temporal if run them as activity not just as function and if one of them has error can rerun just that activity

**Comment by ardan-bkennedy** [comment]
This logic seems to be business oriented. These are all the things that need to happen to purchase a ticket. It defines the rules and the order of operation to complete a business task. 

I would see a domain named Ticket with an API that would own this logic. The App layer Ticket domain handles the input and output to the user.

**Comment by himynamej** [comment]
Thank you I got this
