### ISSUE TITLE
Separate service in api

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/encore#5]
Hey I think we should separate services in api for encore ,encore can show up in diagram how they connect and how it's work ,do you think we can do it in encore ?
For example each domain have a service.

**Comment by ardan-bkennedy** [comment]
I'm assuming you want to build out each domain and a separate Encore service? It's an interesting idea but I don't want to teach that. That being said, you are free to clone the project and experiment with the idea.

**Comment by himynamej** [comment]
I did that and I want to know your thoughts about it ,thank you

**Comment by ardan-bkennedy** [comment]
Since you don't have to worry about deployment and the communication between the services, Encore makes this easy to do. You will lose transactions for
