### ISSUE TITLE
encore test error

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/encore#6]
hi 
in api level auth test There is no chance of error
For each test when encore:authhandler returns an error and test passed  Even when it is not equal to the error we specified

for example when you change ExpResp test still pass 

func updateAuth(sd apitest.SeedData) []apitest.Table {
	table := []apitest.Table{
		{
			Name:    "emptytoken",
			Token:   "&nbsp;",
			ExpResp: errs.Newf(errs.Unauthenticated, "error parsing token: token contains an invalid number of segments"),
			ExcFunc: func(ctx context.Context) any {
				resp, err := sales.UserUpdate(ctx, "", userapp.UpdateUser{})
				if err != nil {
					return err
				}

				return resp
			},
			CmpFunc: apitest.CmpAppErrors,
		},

**Comment by himynamej** [comment]
ctx, err := at.authHandler(ctx, tt.Token)
			if err != nil {
				diff := tt.CmpFunc(err, tt.ExpResp)
				if diff != "" {
					log(diff, err, tt.ExpResp)
				}
				return
			}
i think  this return is ower problem ,in apitest

**Comment by ardan-bkennedy** [comment]
The real bug was calling the `log` function since I had to stop using it. Not sure how I missed that. Look at main and see the change.
